### ISSUE TITLE
Release 1.0 tracking

### ISSUE THREAD

**Issue by andreaTP** [dylibso/chicory#579]
We plan to start releasing Milestone or RC 1.0 of Chicory.
I'll update this issue with the remaining tasks.

First target release:
- Target release date 1.0.0-M1 ~~25/10/2024~~ released: 04/11/2024

Blocking activities:

- [x] add `-experimental` to the experimenta modules and skip the release of testing packages
    - aot - experimental
    - aot-maven-plugin - experimental
    - aot-tests - skip
    - bom - 1.0
    - cli - experimental
    - docs-lib - skip
    - function-annotations - experimental
    - function-processor - experimental
    - fuzz - skip
    - jmh - skip
    - log - 1.0
    - machine-tests - skip
    - runtime - 1.0
    - runtime-tests - skip
    - test-gen-plugin - skip
    - wabt - 1.0
    - wasi - 1.0
    - wasi-test-gen-plugin - skip
    - wasm - 1.0
    - wasm-corpus - skip
- [x] include all released modules in BOM
- [x] minimum docs: can be under construction but should have some shape - @andreaTP 
- [x] remove docs from Readme: and craft a proper one
- [x] review public API - @evacchi / @andreaTP 
- [x] global review file by file - @evacchi / @andreaTP 
- [x] PRs cleanup
- [x] Issues: labelling update/cleanup
- [x] update Roadmap

Non blocking activities:
- [ ] finalize AOT
- [ ] host-module annotations/bindgen refactoring etc.
- [ ] SIMD
- [ ] new logo and graphics - @nilslice ?
- [ ] triage-process for Issues
- [ ] Security Policy
- [ ] Verify DCO/legals etc. - @bhelx 
- [ ] Maven wrapper

**Comment by andreaTP** [comment]
After the release of the first Milestone I close this one in favor of #651
